### PR TITLE
Simplify gitops by removing rebase logic. Use git pull --ff-only

### LINKED ISSUE #39: Use git pull --ff-only
https://blog.sffc.xyz/post/185195398930/why-you-should-use-git-pull-ff-only-git-is-a

- If on default_branch perform git pull --ff-only or show conflict message
- If on custom branch perform git pull --ff-only 
  - If failure show conflict message
  - On success proceed with git rebase/merge origin/<default_branch>

If rebase and or merge with origin/<default_branch> fails show conflict with default_branch message

### PR DESCRIPTION
**Pull request by firecow**
CLOSES #39 
Also added source-map-support

### CODE REVIEW

File: src/gitops.ts [hunk 1]
```diff
@@ -9,27 +9,21 @@ import { printHeader, printLogs } from "./utils";
 import { applyPromiseToEntriesWithProgressBar } from "./progress";
 
 async function hasLocalChanges(dir: string) {
-	const res = await pcp.spawn("git", ["status", "--porcelain"], {
-		cwd: dir,
-		encoding: "utf8",
-	});
+	const res = await pcp.spawn("git", ["status", "--porcelain"], { cwd: dir, encoding: "utf8" });
```
Comment (LauJosefsen) [inline src/gitops.ts:12]: No catch for child process

Comment (LauJosefsen) [reply src/gitops.ts:12]: Not your change, but all git actions can fail afaik. Just resolve this if you don't wanna fix :)

**Review by LauJosefsen — APPROVED** [review]
